### ISSUE TITLE
Failed to build on Debian Testing

### ISSUE THREAD

**Issue by PlutoniumHeart** [gadgetron/gadgetron#227] opened 2015-10-10 14:17 UTC
Hi 
I am having some problem building gadgetron on Debian Testing, I can't even get pass the cmake process, the last few lines of cmake output is as follow:
```
...
CMake Error at chroot/CMakeLists.txt:31 (get_filename_component):
  get_filename_component unknown component -lpthread


CPACK_PACKAGING_INSTALL_PREFIX: /usr/local
Found CPack generators: DEB
Configuring incomplete, errors occurred!
See also "/home/zhitaoli/workspace/Git/gadgetron/build/release/CMakeFiles/CMakeOutput.log".
```
I cannot get anything useful from the log file, thus I am putting this here to see if any of you guys know what is going on.

On another note, I think Debian Testing is migrating to GCC 5.0, meaning some major libraries like boost provided by debian is also going to be built using gcc 5.0, as far as I know CUDA is not compatible with gcc 5.0(even the newest version 7.5), I am not sure how this is going to impact gadgetron, but I am already experiencing problem building ISMRMrd with older gcc versions(4.8, 4.9), due to libboost been compiled with gcc 5.0. So the situation is to use the system libs like boost, gcc 5.0 is required, but then to have CUDA gcc 4.8 is required, thus making boost(and maybe some other libs too) and CUDA mutually exclusive...

**Comment by inati** [comment] 2015-10-10 15:00
Two other options:
1) use the docker image (or vm) approach
https://github.com/gadgetron/gadgetron/wiki/Using-Docker <https://github.com/gadgetron/gadgetron/wiki/Using-Docker>
you can log into the docker image and use the full development environment.

2) use anaconda to create a native self-contained environment:
http://conda.pydata.org/miniconda.html <http://conda.pydata.org/miniconda.html>
I recently started setting this up here.  See this for more info:
https://github.com/conda/conda-recipes <https://github.com/conda/conda-recipes>
https://github.com/gadgetron/gadgetron-conda-recipes <https://github.com/gadgetron/gadgetron-conda-recipes>
and the beginnings of a channel with many of the bits here:
https://anaconda.org/inati <https://anaconda.org/inati>

**Comment by PlutoniumHeart** [comment] 2015-10-10 15:06
I assume you are talking about the "On another note" part. I am actually using parts of gadgetron, the nufft lib to be specific, I need to be able to build gadgetron on my machine, so I don't think those work around works...

**Comment by hansenms** [comment] 2015-10-10 15:59
Well, being on testing, this is the sort of thing that happens from time to time. Once Ubuntu 15.10 (which will probably have GCC 5) is out, we will probably start having a look at this. As long as CUDA is not supported with GCC 5, we will not be switching. But I'm sure it will be in the next few months (maybe CUDA 7.5, we will see).

It's inconvenient, but the cost of being at the bleeding edge.

Our reference platform is Ubuntu LTS (currently 14.04) if you rely on the Gadgetron for your stuff, that's the platform to be on. But again, it will work with GCC 5, when all the dependencies settle down and we start looking at it.

------

**Comment by inati** [comment] 2015-10-10 19:13
Yes, I was referring to the "on another note" part - the bit about not wanting to clobber your os, but needing to build with older compilers.  The point I was trying to make was that there are several ways to build gadgetron and all of its dependencies on your bleeding edge machine, without using the system's default compiler chain or apt repositories.  The anaconda solution will be natively on your machine, just with a different set of paths.  If I make an anaconda environment called test, which lives for example in ~/conda/test, then I can run a program like this: ~/conda/test/bin/gadgetron or ~/conda/test/bin/siemens_to_ismrmrd.  I can do this on a centos 5 system, or a bleeding edge ubuntu system, or an opensuse whatever.  I can do this  in a way that lets me you use the same binaries across all the different versions of 64-bit linux.

**Comment by dchansen** [comment] 2015-10-10 19:49
Gadgetron and Cuda work fine with GCC 5, but you have to modify a single Cuda header file. See [here](https://www.pugetsystems.com/labs/articles/Install-NVIDIA-CUDA-on-Fedora-22-with-gcc-5-1-654/) how it's done for Fedora. 

As for the Makefile problem, I'm unsure what's wrong (I think the path to CUDA might be set wrong), but if you don't need the chroot part, you can just comment out the line including the chroot dir in the master CMakelist.txt

**Comment by PlutoniumHeart** [comment] 2015-10-11 00:00
@dchansen Thanks for the link, that was very helpful for using cuda, any idea what's going on with the cmake error?

**Comment by dchansen** [comment] 2015-10-11 04:49
As far as I can tell, the CUDA_LIBRARIES cmake variable somehow includes "-lpthread", which is clearly a bug. My guess is that your cmake variables are set up wrong somehow. 
That doesn't mean this isn't an issue with Gadgetron, but for starters make sure that all the CUDA cmake variables are set correctly.

**Comment by PlutoniumHeart** [comment] 2015-10-17 15:29
@hansenms I am actually using cuda 7.5, it's already released, and it doesn't support gcc5, highest version supported is 4.9.1 I think(not even 4.9.2).
@dchansen I have check all variables related to cuda, and I don't see anything fishy, I think it's either a bug with gadgetron or a bug with cmake 3.3.2, because I believe it started after an upgrade to cmake.

**Comment by hansenms** [comment] 2015-10-17 16:49
As I said, by the time we get there, it will be supported. There is no particular need to upgrade at this point.

**Comment by dchansen** [comment] 2015-10-17 17:28
On Fedora, Gadgetron compiles with cmake 3.3.2, so it must somehow be related to Debian.

**Comment by dchansen** [comment] 2015-10-19 17:24
Nope, turns out it was cashed. Seems to be a change to FindCUDA in CMake that would require a change in the chroot script.

**Comment by hansenms** [comment] 2015-10-19 19:45
Don't we have our own FindCUDA?

**Comment by dchansen** [comment] 2015-10-20 05:55
Our FindCUDA is built on top of the standard one. All it does is give us the supported GPU versions.

**Comment by hansenms** [comment] 2015-10-20 12:00
I'm just a bit confused about the relation to chroot. What is that all about?

**Comment by dchansen** [comment] 2015-10-20 12:18
The problem is line 27-40 in https://github.com/gadgetron/gadgetron/blob/master/chroot/CMakeLists.txt
The CUDA_LIBRARIES variable has changed in the CMake (apparently), so get_filename_component fails.

**Comment by hansenms** [comment] 2015-10-20 13:00
OK, but that should be a small fix, right? Since we also have our own FindCUDA wrapper, we could simply make sure that it defines that variable, but that might be messy.

**Comment by hansenms** [comment] 2015-10-20 13:01
Just a note CUDA_LIBRARIES is used in quire a few places.

**Comment by dchansen** [comment] 2015-10-20 19:00
So, I looked at it a little more, and the problem is that get_filename_component expects the path to a single file or directory, but CUDA_LIBRARIES now contains a bunch of these.

**Comment by PlutoniumHeart** [comment] 2015-10-22 16:46
Just a update for the current situation: I am currently using a custom older version of cmake to avoid this bug, I also used the gcc-5 cuda workaround suggested, and everything seems to work fine.

**Closed** 2016-01-21 20:13 UTC
