### ISSUE TITLE
Python Gadget Error 

### ISSUE THREAD

**Issue by MalteRoehl** [gadgetron/gadgetron#576] opened 2018-02-12 18:34 UTC
Dear all,
I am currently starting to work with the Gadgetron and have run into a little problem.
Based on the Generic_Cartesian_Grappa_EPI.xml I wanted to change something with a python gadget after the BucketToBuffer gadget.
So initially I used a simple Passthrough gadget, based on the examples that come with the Gadgetron. However, when I add the gadget the reconstruction fails.
Without the Passthrough gadget it works fine.
Does anyone have any ideas how to fix this issue ?
Best wishes,
Malte

[Python_Gadget_Error_files.zip](https://github.com/gadgetron/gadgetron/files/1717340/Python_Gadget_Error_files.zip)

Os: Linux 16.04 LTS running the Docker gadgetron1604_cuda build

**Comment by dchansen** [comment] 2018-02-14 14:12
I can reproduce the bug - finding the cause is proving harder.

**Comment by MalteRoehl** [comment] 2018-02-15 11:44
Thanks very much for working on this. If I can help in any way let me know. I am trying to figure out the cause myself, but my knowledge is still quite limited.

**Comment by dchansen** [comment] 2018-02-15 12:22
Should be fixed now in Master.

**Closed** 2018-02-16 12:58 UTC
